CONTROL = "CONTROL"
REQUIRED = "REQUIRED"
NAPOI = "NOT A PEAK OF INTEREST"

## Amino acids 
ALA = "Alanine"
ARG = "Arginine"
ASN = "Asparagine"
ASP = "Aspartic acid"
CYS = "Cysteine"
GLN = "Glutamine"
GLU = "Glutamic acid"
GLY = "Glycine"
HIS = "Histidine"
ILE = "Isoleucine"
LEU = "Leucine"
LYS = "Lysine"
MET = "Methionine"
PHE = "Phenylalanine"
PRO = "Proline"
SER = "Serine"
THR = "Threonine"
TRP = "Tryptophan"
TYR = "Tyrosine"
VAL = "Valine"
H2 = "H2"
